### ISSUE TITLE
Upgrading from 3.4.0 to 3.4.1 breaks PHP 7.3

### ISSUE THREAD

**Issue by roberthenniger** [chillerlan/php-qrcode#83]
Seems that the library upgrades internally to the php-settings-container v2.1.2 and this is not compatible with PHP 7.3.
Getting an exception with the following content:

**syntax error, unexpected 'SettingsContainerInterface' (T_STRING),  expecting function (T_FUNCTION) or const (T_CONST)**

I would have prefered if the version number would have gone up to 3.5.0 or even 4.0 since some of the loaded libs are clearly not compatible anymore. Wa snow downgrading on our environment.

**Comment by codemasher** [comment]
Wait, this shouldn't be. I think i know what the problem is. I accidentally tagged the main branch?? I'm gonna fix this right now! ([the 3.x branch works perfectly fine from PHP7.2 onwards](https://github.com/chillerlan/php-qrcode/actions/runs/1198929956))

**Comment by codemasher** [comment]
Done. The [proper v3.4.1](https://packagist.org/packages/chillerlan/php-qrcode#3.4.1) should be available soon. Sorry for the inconvenience!

**Comment by roberthenniger** [comment]
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating chillerlan/php-settings-container (1.2.2 => 2.1.2): Downloading (100%)         
  - Updating chillerlan/php-qrcode (3.4.0 => 3.4.1): Downloading (100%)     
Still not working. Was clearing composer cache over (composer clearcache) but it dod not resolve and still pulls the 2.1.2 from chillerlan/php-settings-container package

**Comment by codemasher** [comment]
This is weird. Do you have some locked dependencies by chance?

**Comment by roberthenniger** [comment]
No, no locked dependencies. It upgrades and downgrades just fine.


From: smiley ***@***.***>
Date: Thursday, 9 September 2021 at 11:22
To: chillerlan/php-qrcode ***@***.***>
Cc: Robert Henniger ***@***.***>, Author ***@***.***>
Subject: Re: [chillerlan/php-qrcode] Upgrading from 3.4.0 to 3.4.1 breaks PHP 7.3 (#83)

This is weird. Do you have some locked dependencies by chance?

**Comment by codemasher** [comment]
Can you please try to fetch from the latest commit directly and see if this works? 
`composer require chillerlan/php-qrcode:v3.2.x-dev#468603b687a5fe75c1ff33857a45f1726c7b95a9`
